name = "azaria-ai-worker"
main = "src/worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

workers_dev = true

[[kv_namespaces]]
binding = "AZARIA_KV"
id = "c5e138ac78634ce4802de4171941b4a9"

[env.production]
name = "azaria-ai-worker"

[env.preview]
name = "azaria-ai-worker-preview"

[triggers]
crons = ["0 6 * * *"]

[observability]
enabled = true
head_sampling_rate = 0.1
